# Look at: http://library.isr.ist.utl.pt/docs/roswiki/costmap_2d.html for parameter list
# This being the common costmap makes it so both global and local have the same parameters set here

# Set dimensions of robot here along with padding to cushion more space
footprint: [[-1, -0.15], [-1, 0.45], [0.15, 0.45], [0.15, -0.15]]
footprint_padding: 0.01

robot_base_frame: base_link

# Map update frequency and visualization publish frequency
update_frequency: 2
publish_frequency: 2

# Might need transform tolerance to fix transform errors ???

resolution: 0.03

# Distance in meters that sensors will detect obstacles and broadcast view respectively
obstacle_range: 4.0
raytrace_range: 4.0



#layer definitions
static_layer:
    map_topic: /map

obstacle_layer:
  enabled: true
  observation_sources: bump
  bump: {
    data_type: PointCloud2,
    topic: /camera/depth/color/points,

    # marking and clearing set to true records and removes obstacles respectively
    marking: true,
    clearing: true,

    # Set to not count ceiling or floor as obstacles
    min_obstacle_height: -0.3,
    max_obstacle_height: 0.4
  }

inflation_layer:
  enabled: true
  # Minimum distance allowed between obstacles and robot footprint
  inflation_radius: 1.75
  cost_scaling_factor: 2.58