footprint: [[-0.12, -0.12], [-0.12, 0.12], [0.12, 0.12], [0.12, -0.12]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 2
publish_frequency: 1
transform_tolerance: 0.5

resolution: 0.03

obstacle_range: 4.0
raytrace_range: 4.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 5.5
  combination_method: 1
  observation_sources: bump
  bump: {
    data_type: PointCloud2,
    topic: /camera/depth/color/points,
    marking: true,
    clearing: false,
    min_obstacle_height: 0.0,
    max_obstacle_height: 0.1
  }

inflation_g:
    inflation_radius: 0.06
    
inflation_l:
    inflation_radius: 0.03
