global_frame: map
rolling_window: true
track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_g,               type: "costmap_2d::InflationLayer"}
