# Look at: http://library.isr.ist.utl.pt/docs/roswiki/costmap_2d.html for parameter list
# This being the common costmap makes it so both global and local have the same parameters set here

# Set dimensions of robot here in meters along with padding to cushion more space
footprint: [[0.55, -0.30], [0.55, 0.30], [-0.55, -0.30], [-0.55, 0.30]]
footprint_padding: 0.03

# The tf that should be at ground level and at center of robot
robot_base_frame: base_link

# Map update (topic) frequency and visualization (rviz) publish frequency
update_frequency: 5
publish_frequency: 2

# Time buffer for how off a tf is in seconds (ex. base_link tf is at 15 seconds but we want 15.5 seconds, 
# so we extrapolate .5 seconds into the past to get it)
transform_tolerance: 1.0

# Quality of map, don't want it too high or it will lag
resolution: 0.03

#layer definitions
static:
# Setting map to camera_odom_frame which will be static relative to camera_pose_frame
    map_topic: /map

obstacle_layer:
  enabled: true
  observation_sources: bump craters
  bump: {
    data_type: PointCloud2,
    topic: /camera/depth/color/points,

    # marking and clearing set to true records and removes obstacles respectively
    clearing: true,

    # Set to not count ceiling or floor as obstacles
    min_obstacle_height: 0.3,
    max_obstacle_height: 0.5,
  }
  craters: {
    data_type: PointCloud2,
    topic: /camera/depth/color/points,

    # marking and clearing set to true records and removes obstacles respectively
    clearing: true,

    # Set to not count ceiling or floor as obstacles
    min_obstacle_height: -0.4,
    max_obstacle_height: -0.2,
  }

inflation_layer:
  inflation_radius: 0.10
