# Look at: http://library.isr.ist.utl.pt/docs/roswiki/costmap_2d.html for parameter list
# This being the common costmap makes it so both global and local have the same parameters set here

# Set dimensions of robot here along with padding to cushion more space
footprint: [[0.2, -0.13], [0.2, 0.13], [-0.25, -0.13], [-0.25, 0.13]]
footprint_padding: 0.01

robot_base_frame: base_link

# Map update frequency and visualization publish frequency
update_frequency: 2
publish_frequency: 2

# Might need transform tolerance to fix transform errors ???

resolution: 0.03

# Distance in meters that sensors will detect obstacles and broadcast view respectively
obstacle_range: 2.0
raytrace_range: 3.0

# Minimum distance allowed between obstacles and robot footprint
inflation_radius: 0.16

#layer definitions
static:
# Setting map to camera_odom_frame which will be static relative to camera_pose_frame
    map_topic: /camera_odom_frame

obstacle_layer:
  enabled: true
  observation_sources: bump
  bump: {
    data_type: PointCloud2,
    topic: /camera/depth/color/points,

    # marking and clearing set to true records and removes obstacles respectively
    marking: true,
    clearing: true,

    # Set to not count ceiling or floor as obstacles
    min_obstacle_height: 0.2,
    max_obstacle_height: 0.4
  }
