# Look at: http://library.isr.ist.utl.pt/docs/roswiki/costmap_2d.html for parameter list

# Global frame for local_costmap MUST be odom frame which is a combination of all the sensors
# from robot_localization and gets the updated position of the robot right now, we have the 
# camera_pose_frame but the tf tree needs to be reworked and probably swap this frame to odom
global_frame: camera_pose_frame

# Rolling window set to true means the frame will follow the robot
rolling_window: true

# Static map set to false means map is able to move around the empty space
# If it was static then it would be the fixed frame everything is attached to on the tf tree
static_map: false

# Dimensions of local_costmap map, but I think this is done wrong, needs fixing and then 
# dimensions of global costmap set to size of arena
width: 5
height: 5

# Takes in obstacle_layer and inflation_layer from common_costmap.yaml
plugins:
  - {name: obstacle_layer,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,          type: "costmap_2d::InflationLayer"}
