# This file tells ROS what state/phase the robot is currently on using parameters. Ex. dig, deposit, move

localizationPhase: false 

settingNavigationDigPhase: false
ongoingNavigationDigPhase: false

settingDigPhase: false
ongoingDigPhase: false

settingNavigationDepositPhase: false
ongoingNavigationDepositPhase: false

settingDepositPhase: false
ongoingDepositPhase: false

settingDriveModePhase: false
ongoingDriveModePhase: false

manualMode: true