# This file tells ROS what state/phase the robot is currently on using parameters. Ex. dig, deposit, move
# As of March 21, only ongoingDigPhase, ongoingDepositPhase, and manualMode are being used by autoInputs.py and
# dig and deposit functions in trencherOperationsClass.cpp

localizationPhase: false 

settingNavigationDigPhase: false
ongoingNavigationDigPhase: false

settingDigPhase: false
ongoingDigPhase: false

settingNavigationDepositPhase: false
ongoingNavigationDepositPhase: false

settingDepositPhase: false
ongoingDepositPhase: false

settingDriveModePhase: false
ongoingDriveModePhase: false

manualMode: true